ALTER TABLE "categories" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "categories" ALTER COLUMN "default_budget" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "category_groups" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "debtor_entries" ALTER COLUMN "amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "debtor_entries" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "fixed_expenses" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "fixed_expenses" ALTER COLUMN "amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "goal_contributions" ALTER COLUMN "amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "goals" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "goals" ALTER COLUMN "target_amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "incomes" ALTER COLUMN "source" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "incomes" ALTER COLUMN "amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "incomes" ALTER COLUMN "investment_return_capital" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "installment_groups" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "installment_groups" ALTER COLUMN "total_amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "investment_types" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "investment_withdrawals" ALTER COLUMN "amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "investment_withdrawals" ALTER COLUMN "tax_amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "investments" ALTER COLUMN "amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "investments" ALTER COLUMN "yield_amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "monthly_budget_overrides" ALTER COLUMN "amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "payment_accounts" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "people" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "people" ALTER COLUMN "email" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "people" ALTER COLUMN "phone" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "amount" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_settings" ALTER COLUMN "pix_key" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN "encrypted_dek" text;